package me.kev.sva.chat.tooling;

import java.util.List;
import java.util.Locale;

import me.kev.sva.ServerAssistantPlugin;

/**
 * Base class for tools that can be used by the assistant.
 *
 * <p>
 * Each tool defines its command name, usage information, expected
 * arguments, and execution logic. The base class handles common argument
 * parsing, validation, command matching, and result formatting.
 * </p>
 */
public abstract class ToolBase {

  protected final ServerAssistantPlugin plugin;

  /**
   * Creates a new tool.
   *
   * @param plugin the SVA plugin instance
   */
  public ToolBase(ServerAssistantPlugin plugin) {
    this.plugin = plugin;
  }

  /**
   * Returns the command used to invoke this tool.
   *
   * <p>
   * For example, a wiki tool would return {@code "wiki"}.
   * </p>
   *
   * @return the tool command name
   */
  public abstract String getCommand();

  /**
   * Returns the instructions describing how the assistant should use
   * this tool.
   *
   * <p>
   * This content is included in the assistant's available-tools
   * context.
   * </p>
   *
   * @return the tool usage description
   */
  protected abstract String getUsageDescription();

  /**
   * Returns the number of tokens expected by this tool, including the
   * tool command itself.
   *
   * <p>
   * For example, {@code "wiki economy"} contains two arguments:
   * {@code "wiki"} and {@code "economy"}.
   * </p>
   *
   * @return the expected argument count
   */
  protected abstract int getExpectedArgumentCount();

  /**
   * Executes this tool using the provided tool call.
   *
   * @param toolCall the complete tool call generated by the assistant
   * @return the formatted tool result
   */
  public abstract String perform(String toolCall);

  /**
   * Checks whether a tool call contains the expected number of arguments.
   *
   * @param toolCall the complete tool call
   * @return {@code true} if the argument count is valid
   */
  protected boolean checkArgumentCount(String toolCall) {
    return checkArgumentCount(extractArguments(toolCall));
  }

  /**
   * Checks whether the provided arguments contain the expected number
   * of arguments for this tool.
   *
   * @param args the parsed tool arguments
   * @return {@code true} if the argument count is valid
   */
  protected boolean checkArgumentCount(List<String> args) {
    return args.size() == getExpectedArgumentCount();
  }

  /**
   * Returns the usage instructions for this tool.
   *
   * @return the formatted usage description
   */
  public String getUsage() {
    return """
        [TOOL USAGE (%s)]
        %s

        %s
        [END TOOL USAGE (%s)]
        """.formatted(
        getCommand(),
        getUsageDescription(),
        getActivationUsage(),
        getCommand());
  }

  /**
   * Returns instructions describing how this tool may be activated
   * according to its configuration.
   */
  public String getActivationUsage() {
    String path = "tools." + getCommand() + ".activation";

    String activation = plugin.getConfig()
        .getString(path, "never")
        .toUpperCase(Locale.ROOT);

    return switch (activation) {
      case "SMART" -> """
          Tool Usage Mode: SMART
          Use this tool when it is appropriate and useful.
          """;

      case "ASK" -> """
          Tool Usage Mode: ASK
          Ask an online server administrator for permission before using this tool.
          """;

      case "NEVER" -> """
          Tool Usage Mode: NEVER
          This tool is currently unavailable and must not be used.
          """;

      default -> """
          Tool Usage Mode: NEVER
          This tool has an invalid activation mode and must not be used.
          """;
    };
  }

  public boolean canBeUsed() {
    if (!plugin.getConfig().getBoolean("tools.enabled", true)) {
      return false;
    }

    String activation = plugin.getConfig()
        .getString(
            "tools." + getCommand() + ".activation",
            "never");

    return !activation.equalsIgnoreCase("never");
  }

  /**
   * Checks whether the provided tool call belongs to this tool.
   *
   * <p>
   * Tool names are matched case-insensitively.
   * </p>
   *
   * @param toolCall the complete tool call
   * @return {@code true} if this tool should handle the call
   */
  public boolean check(String toolCall) {
    List<String> args = extractArguments(toolCall);

    return !args.isEmpty()
        && args.getFirst().equalsIgnoreCase(getCommand());
  }

  /**
   * Splits a tool call into its individual whitespace-separated
   * arguments.
   *
   * @param toolCall the complete tool call
   * @return the parsed arguments
   */
  protected List<String> extractArguments(String toolCall) {
    return List.of(toolCall.trim().split("\\s+"));
  }

  /**
   * Wraps a raw tool result in the standard tool-result format expected
   * by the assistant.
   *
   * @param result the raw result returned by the tool
   * @return the formatted tool result
   */
  protected String wrapResult(String result) {
    String toolResult = result.isEmpty()
        ? "No result provided. Tool was wrongly called or unavailable."
        : result;

    return """
        [TOOL RESULT (%s)]
        %s
        [END TOOL RESULT (%s)]
        """.formatted(
        getCommand(),
        toolResult,
        getCommand());
  }
}